server {
    listen 80;
    server_name mcda-calculator-test.psi.ch;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name mcda-calculator-test.psi.ch;

    ssl_certificate /etc/nginx/certs/mcda-calculator-test.psi.ch.crt;
    ssl_certificate_key /etc/nginx/private/mcda-calculator-test.psi.ch.key;

    location / {
        proxy_pass http://mcda-calculator:8050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
