server {
    listen 80;
    server_name pif-elog.psi.ch;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name pif-elog.psi.ch;
    
    client_max_body_size 64M;
    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    ssl_certificate /etc/nginx/certs/pif-elog.psi.ch.crt;
    ssl_certificate_key /etc/nginx/private/pif-elog.psi.ch.key;

    location / {
        proxy_pass https://pif-elog:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
