server {
    listen 80;
    server_name sinqimaging.psi.ch;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name sinqimaging.psi.ch;

    ssl_certificate     /etc/nginx/certs/sinqimaging.psi.ch.crt;
    ssl_certificate_key /etc/nginx/private/sinqimaging.psi.ch.key;

    access_log /var/log/nginx/sinqimaging.access.log;
    error_log  /var/log/nginx/sinqimaging.error.log;

    # Proxy EVERYTHING to the Apache container
    location / {
        proxy_pass http://apache_app:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Important for CGI apps
        proxy_buffering off;
    }
}

