# INC0150202 Kohlbrecher Joachim & Wall Edward Owen
server {
    listen 80;
    server_name actris.psi.ch;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name actris.psi.ch;

    root /opt/webcontent/actris;
    index index.html;

    ssl_certificate /etc/nginx/certs/lx-docker-dmz-01.psi.ch.crt;
    ssl_certificate_key /etc/nginx/private/lx-docker-dmz-01.psi.ch.key;

    access_log /var/log/nginx/actris.access.log;
    error_log  /var/log/nginx/actris.error.log;

    location / {
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;

        try_files $uri $uri/ =404;
    }
}

