server {
    listen 80;
    server_name pepisco.psi.ch;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name pepisco.psi.ch;

    ssl_certificate /etc/nginx/certs/lx-docker-dmz-01.psi.ch.crt;
    ssl_certificate_key /etc/nginx/private/lx-docker-dmz-01.psi.ch.key;

    location / {
        proxy_pass http://pepisco:5555;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
